Replicas: 1
ExpectedClusterSize: 1
RevisionHistoryLimit: 3

Image:
  repository: localhost
  name: fragment-home
  tag: v1
  pullPolicy: Never

name: fragment-home
namespace: default

service:
  type: ClusterIP
  port: 3001

# Set toggle for volume mounting
isDev: true

# Supply our local development paths
volume:
  name: host-volume
  path: /opt/microfrontends/fragment-home/dist
  mountPath: /usr/src/app/dist
